### PR TITLE
Amend Dockerfile to support alternative base images

### PR DESCRIPTION
**Pull request by jason-fox**
## Proposed changes

This PR updates the `Dockerfile` so it is flexible enough to be able to use [alternative base images](https://kuberty.io/blog/best-os-for-docker/) should you wish. The base image still defaults  to using the `node:slim` distro, but other base images can be injected using `--build-arg` parameters on the command line. For example, to create a container based on [Red Hat UBI (Universal Base Image) 8](https://developers.redhat.com/articles/2021/11/08/optimize-nodejs-images-ubi-8-nodejs-minimal-image)
add `BUILDER`, `DISTRO`, `PACKAGE_MANAGER` and `USER` parameters as shown:

```console
sudo docker build -t iot-agent \
  --build-arg BUILDER=registry.access.redhat.com/ubi8/nodejs-14 \
  --build-arg DISTRO=registry.access.redhat.com/ubi8/nodejs-14-minimal \
  --build-arg PACKAGE_MANAGER=yum \
  --build-arg USER=1001 .
```

To create a container based on [Alpine Linux](https://alpinelinux.org/about/) add `BUILDER`, `DISTRO`, `PACKAGE_MANAGER`
parameters as shown:

```console
docker build -t iot-agent \
  --build-arg BUILDER=node:16-alpine \
  --build-arg DISTRO=node:16-alpine \
  --build-arg PACKAGE_MANAGER=apk . --no-cache
```

This allows users to upgrade to **their preferred Linux distro** and helps to reduces Critical Vulnerabilities, and therefore makes the final product more secure.

## Further comments

At the moment the base image is still `node-slim`. You may wish to alter this at some point by amending the default build args. Hadolint complains that the images are no longer pinned to versions but this is a false positive as the builder is now under control of the version to use and could even supply the appropriate SHA if they wish.

This is really just an extension of the multi-stage concept introduced in https://github.com/telefonicaid/iotagent-json/pull/485  which added a `--build-arg` to allow users to select a Node.js version.

### CODE REVIEW

**Comment by jason-fox** [comment]
Building the IoT-Agent variants and running the following shows the difference:

```console
docker inspect iot-agent --format '{{ index .Config.Labels }}
```

Here is an example for the ISOXML IoT-Agent:

### Node Slim

```json
"Labels": {
    "maintainer": "FIWARE Foundation e.V.",
    "org.nodejs.version": "14",
    "org.opencontainers.image.authors": "",
    "org.opencontainers.image.description": "IoT Agent for the ISOXML/ADAPT protocol for agricultural machinery (over an HTTP transport)",
    "org.opencontainers.image.documentation": "https://iotagent-isoxml.readthedocs.io/",
    "org.opencontainers.image.licenses": "AGPL-3.0-only",
    "org.opencontainers.image.source": "https://github.com/FIWARE/iotagent-isoxml",
    "org.opencontainers.image.title": "IoT Agent for the ISOXML/ADAPT protocol",
    "org.opencontainers.image.vendor": "Telefónica Investigación y Desarrollo, S.A.U"
}
```

### Red Hat UBI

```json
"Labels": {
    "architecture": "x86_64",
    "build-date": "2021-12-01T09:48:24.222657",
    "com.redhat.build-host": "cpt-1003.osbs.prod.upshift.rdu2.redhat.com",
    "com.redhat.component": "nodejs-14-minimal-container",
    "com.redhat.deployments-dir": "/opt/app-root/src",
    "com.redhat.dev-mode": "DEV_MODE:false",
    "com.redhat.dev-mode.port": "DEBUG_PORT:5858",
    "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
    "description": "Node.js 14 available as container is a base platform for running various Node.js 14 applications and frameworks. Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.",
    "distribution-scope": "public",
    "help": "For more information visit https://github.com/sclorg/s2i-nodejs-container",
    "io.k8s.description": "Node.js 14 available as container is a base platform for running various Node.js 14 applications and frameworks. Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.",
    "io.k8s.display-name": "Node.js 14 Minimal",
    "io.openshift.expose-services": "8080:http",
    "io.openshift.s2i.scripts-url": "image:///usr/libexec/s2i",
    "io.openshift.tags": "builder,nodejs,nodejs14",
    "io.s2i.scripts-url": "image:///usr/libexec/s2i",
    "maintainer": "FIWARE Foundation e.V.",
    "name": "ubi8/nodejs-14-minimal",
    "org.nodejs.version": "14",
    "org.opencontainers.image.authors": "",
    "org.opencontainers.image.description": "IoT Agent for the ISOXML/ADAPT protocol for agricultural machinery (over an HTTP transport)",
    "org.opencontainers.image.documentation": "https://iotagent-isoxml.readthedocs.io/",
    "org.opencontainers.image.licenses": "AGPL-3.0-only",
    "org.opencontainers.image.source": "https://github.com/FIWARE/iotagent-isoxml",
    "org.opencontainers.image.title": "IoT Agent for the ISOXML/ADAPT protocol with PM2",
    "org.opencontainers.image.vendor": "Telefónica Investigación y Desarrollo, S.A.U",
    "release": "31.1638351975",
    "summary": "Minimal image for running Node.js 14 applications",
    "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/nodejs-14-minimal/images/1-31.1638351975",
    "vcs-ref": "5e704499643809019f1c421be9786e163877af5a",
    "vcs-type": "git",
    "vendor": "Red Hat, Inc.",
    "version": "1"
}
```

**Comment by fgalan** [comment]
Thanks for your proposal. We need to analyse the changes proposed in this PR with our devops team. We will come back after that analysis.

**Comment by jason-fox** [comment]
This kind of relates to #516 - depending on how you want to take this forward - it could be the case that the proposed [.github/fiware/config.json](https://github.com/telefonicaid/iotagent-ul/blob/e31f5dde820e99b11ab27637d20eca57d0e3341f/.github/fiware/config.json#L18) `dockerfile` attribute relates to a separate `.github/fiware/Dockerfile` for example.

**Comment by cesarjorgemartinez** [comment]
No LGTM

**Comment by mapedraza** [comment]
The Dockerfile is a critical thing that impacts the deployment of our components in production. Over the time, changes in the Dockerfile have increased the size of the images, increasing the time it takes to deploy platforms. This is a critical point from an operations perspective as it is directly related to the time it takes to upgrade to new releases and other critical operations.

Changes such the one suggested in this PR would directly impact the problem. After building the image locally with the proposed modifications, the image goes from 170-180MB to over 900MB.

**Comment by jason-fox** [comment]
Superceded.

**Pull request closed without merging**
