### PR TITLE
step 2.1.0-next -> 2.2.0

### PR DESCRIPTION
**Pull request by AlvaroVega**
Mimics PR #605

### CODE REVIEW

**Comment by fgalan** [comment]
Missing:

* Flush CHANGES_NEXT_RELEASE
* Upgrade changelog in rpm/SPECS/iotaul.spec

**Comment by fgalan** [comment]
> Missing:
>
>    * Flush CHANGES_NEXT_RELEASE
>   * Upgrade changelog in rpm/SPECS/iotaul.spec

CNR already empty, so first item it's already ok.

In the changelog the entry "Upgrade iotagent-node-lib from 3.1.0 to 3.2.0" should be included

**Comment by AlvaroVega** [comment]
> > Missing:
> > 
> > * Flush CHANGES_NEXT_RELEASE
> > * Upgrade changelog in rpm/SPECS/iotaul.spec
> 
> CNR already empty, so first item it's already ok.
> 
> In the changelog the entry "Upgrade iotagent-node-lib from 3.1.0 to 3.2.0" should be included

Done in https://github.com/telefonicaid/iotagent-ul/pull/609/commits/8593324c57da2cc967822cfd5c689b3dab095d0b

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
