### PR TITLE
Update CSS to avoid redirect

### PR DESCRIPTION
**Pull request by jason-fox**

### CODE REVIEW

**Comment by jason-fox** [comment]
@fgalan - could you give ReadTheDocs a kick to refresh the CSS?

https://readthedocs.org/projects/fiware-iotagent-ul/builds/

**Comment by fgalan** [comment]
Done. Could you confirm, please?

**Comment by fgalan** [comment]
Not sure what do you mean... Currently the build is done with:

imagen

Do you mean to change to CPython 3.x (the other option available in that combo box)? Or do you mean to re-launch the build with CPython 2.x?

**Comment by jason-fox** [comment]
If you look at the log, the failed build is complains about Python 2 - I'm not sure if it was a one-off (and ReadTheDocs is now suppressing the error) or if it is going to cause further problems going forward. 

I'd keep it as Python 2 first, and maybe change it if ReadTheDocs still complains.

**Comment by fgalan** [comment]
Relaunching. Let's see what's happening in some minutes...

**Comment by jason-fox** [comment]
LTGM :smile:


For testing purposes, I've just switched one of my own personal ReadTheDocs projects from Python 2 to Python 3 and it worked, so maybe that is the eventual answer for all of them

```text
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Pygments==2.3.1
```

So maybe they will all need to switch over the next 4 months.

**Pull request merged**
