### PR TITLE
WIP: Configure amqp

### LINKED ISSUE #268: amqp configuration is not supported
1. host is hardcoded
1. user and password are not supported

ect

### PR DESCRIPTION
**Pull request by chicco785**
fix #268

### CODE REVIEW

**Comment by chicco785** [comment]
tests need to be updated

**Comment by AlvaroVega** [comment]
I also miss

**Comment by chicco785** [comment]
@AlvaroVega sure, first i wanted to be sure it works as expected

@AlvaroVega @fgalan regarding the tests, not sure what's going on, because i get the same errors if i run test for master (so without my code changes) locally, i need to investigate, but if you have any clue ;)

**Comment by AlvaroVega** [comment]
Most of the contributions of this branch have been merged. Thanks for your work @chicco785 !

**Comment by chicco785** [comment]
Hi Alvaro,
You are welcome. I will check what was not merged and see if it make sense
to add it.
Sorry if I didn't come back before to you.

**Pull request closed without merging**
