### PR TITLE
Update Dockerfile to use Node 8

### PR DESCRIPTION
**Pull request by AlvaroVega**

### CODE REVIEW

**Comment by AlvaroVega** [comment]
@dcalvoalonso first of all we are going to test with that node version in current image.

**Comment by dcalvoalonso** [comment]
Ok @AlvaroVega , thanks for the info! ;)

**Comment by fgalan** [comment]
> @AlvaroVega Why don't we use https://hub.docker.com/r/library/node/tags/8.12-slim/ as base image?

Becaure it is advisable to go step by step :)

The idea is a first step in which only node version is changed (v4 -> v8), but base image keeps the same. If e2e testing regression goes ok, then next step will be to use simplified images, as the one you propose.

**Comment by dcalvoalonso** [comment]
@fgalan @AlvaroVega Just to know, have you executed the e2e tests with the new Docker image based on Node.js v8?

**Comment by fgalan** [comment]
Good point :) Let me elaborate a little bit.

In e2e test, the typical case is to test one functionality developed in just one component, large and/or sensible enough so reverting it uses to be complex. In this case, the usual procedure is to build an ah hoc docker with that component in a dedicated branch, leaving all the others components the same (i.e. from master), test and, if test is ok, merge into master.

This time we are adopting a different strategy. Given the large amound of systems involved (not only IOTA-UL and IOTA-JSON, but also IOTA-Manager, PEP-Steelskin, Pereso-FE, STH) doing the test one by one using the usual procedure, will take a lot of time. In addition, the cost of rolling back is pretty low in this case (just one env var in Dockerfile) so we can easily get back to v4 is something breaks.

Of course, the risk of breaking the integration is higher than in the usual procedure. However, we think that speeding up this time worth it (and, anycase, if everything breaks it is easy to rollback).

**Comment by dcalvoalonso** [comment]
Ok, no problem at all! :)

If you don't mind, let us know the results of these tests. Once you checked that integration is correct, it would be important to add PM2 to avoid problems with `out of memory` errors as we discovered last week.

**Comment by fgalan** [comment]
Yes, of course. We will keep you informed.

**Pull request merged**
