### PR TITLE
Switch from Travis to GitHub Actions.

### PR DESCRIPTION
**Pull request by jason-fox**
As I'm sure you are aware from the TSC minutes, it appears that Travis is transitioning towards a paid pricing model. It would be opportune for active FOSS Projects to migrate to use the integrated GitHub Actions. It looks like each GitHub account is safe until January,  but then `travis-ci.org` goes read-only then the 100000 credits start counting down. There is no clarity over if/how to obtain more credits, and indeed if they can be obtained in a timely manner.

#### Background links

-  https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
-  https://www.reddit.com/r/programming/comments/jou1k9/travis_cis_new_pricing_plan_threw_a_wrench_in_my/
-  https://www.reddit.com/r/haskell/comments/jvbs49/psa_maintainers_should_think_about_migrating_off/
-  https://www.reddit.com/r/programming/comments/jmwj9m/the_travis_ci_blog_the_new_pricing_model_for/

This PR sets up the equivalent GitHub Action CI to the old Travis Yaml and as a bonus, the flaky AMPQ test. seems to work.

### CODE REVIEW

**Comment by jason-fox** [comment]
The result of a CI test run can be seen here: https://github.com/jason-fox/iotagent-ul/actions/runs/380925209

**Comment by fgalan** [comment]
> ... the flaky AMPQ test. seems to work.

Music to my ears xD

**Comment by fgalan** [comment]
> The result of a CI test run can be seen here: https://github.com/jason-fox/iotagent-ul/actions/runs/380925209

Is there a way to so the result of the action "inline" the PR? I mean something like Travis does:

imagen

or

imagen

**Comment by jason-fox** [comment]
Yes, it will display in the same manner **once the PR is merged**.

Here is a working FIWARE example: https://github.com/FIWARE/iotagent-isoxml

Screenshot 2020-11-24 at 17 21 20

**Comment by fgalan** [comment]
Thanks for the clarifications!

Btw, maybe this other repository should also be de-travis-ed ? https://github.com/telefonicaid/lightweightm2m-iotagent

**Comment by jason-fox** [comment]
> Btw, maybe this other repository should also be de-travis-ed ? https://github.com/telefonicaid/lightweightm2m-iotagent

Probably, but unlike all of the other repos, the Unit-Tests for LWM2M have not been updated to use mocks properly so the set-up for the GitHub Actions would be much more complex. I haven't got time for that. I'm starting off by picking the low hanging fruit from 50+ FIWARE projects **first**. I'm running through the easy Node.js stuff first then Java then Python.

Your biggest concern should be converting repos that eat into your free minutes like: https://github.com/telefonicaid/fiware-orion

**Comment by fgalan** [comment]
> > Btw, maybe this other repository should also be de-travis-ed ? https://github.com/telefonicaid/lightweightm2m-iotagent
> 
> Probably, but unlike all of the other repos, the Unit-Tests for LWM2M have not been updated to use mocks properly so the set-up for the GitHub Actions would be much more complex. I haven't got time for that. I'm starting off by picking the low hanging fruit from 50+ FIWARE [catalogue](https://github.com/Fiware/catalogue) projects **first**. I'm running through the easy Node.js stuff first then Java then Python.

Ok, makes sense. IOTA LWM2M can wait.

> Your biggest concern should be converting repos that eat into your free minutes like: https://github.com/telefonicaid/fiware-orion

You are right. Currently, the functional testing sub-job in Orion takes around 40-50 minutes (even with some "hacks" to reduce the time of some test cases, such [this one](https://github.com/telefonicaid/fiware-orion/blob/master/ci/rpm7/build.sh#L75)), very close to the the travis timeout. Have github actions some similar timeout? Lower or higher than travis?

**Comment by jason-fox** [comment]
`jobs.<job_id>.steps.timeout-minutes` and `jobs.<job_id>.timeout-minutes` define the limits, according to the [docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)

> The maximum number of minutes to let a job run before GitHub automatically cancels it. Default: 360

So six hours.

**Comment by fgalan** [comment]
> So six hours.

Great. That means that the functional testing sub-job in Orion will fit even better in git actions than in travis :)

**Comment by fgalan** [comment]
> > > Btw, maybe this other repository should also be de-travis-ed ? https://github.com/telefonicaid/lightweightm2m-iotagent
> > 
> > 
> > Probably, but unlike all of the other repos, the Unit-Tests for LWM2M have not been updated to use mocks properly so the set-up for the GitHub Actions would be much more complex. I haven't got time for that. I'm starting off by picking the low hanging fruit from 50+ FIWARE [catalogue](https://github.com/Fiware/catalogue) projects **first**. I'm running through the easy Node.js stuff first then Java then Python.
> 
> Ok, makes sense. IOTA LWM2M can wait.

Noted for IOTA-LWM2M: https://github.com/telefonicaid/lightweightm2m-iotagent/issues/235

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
