### PR TITLE
Add explicit protocol note for MQTT topics

### PR DESCRIPTION
**Pull request by jason-fox**
Related https://github.com/FIWARE/tutorials.NGSI-v2/pull/8

### CODE REVIEW

**Comment by jason-fox** [comment]
I've also included an explicit `requirements.txt` for ReadTheDocs because the build no longer succeeds without an explicit Jinja version. If this succeeds I can make the same change on the IoT Agent for JSON.

**Comment by jason-fox** [comment]
Probably, but you'll need to merge to see if readthedocs works.

**Comment by jason-fox** [comment]
I guess that is because you are using an outdated python to build.

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by AlvaroVega** [comment]
I guess the same not should be added to others iotagents.

**Comment by jason-fox** [comment]
Probably just the IoT Agent for JSON which has the same MQTT binding (unless there are others?)

**Comment by fgalan** [comment]
> Probably, but you'll need to merge to see if readthedocs works.

After merging the PR, it seems RTD build is working:

imagen

**Comment by AlvaroVega** [comment]
> I guess the same should be added to others iotagents.

It was a typo, sorry.

**Pull request merged**
