### PR TITLE
FIX default port in Dockerfile and related stuff

### PR DESCRIPTION
**Pull request by fgalan**
According to https://github.com/telefonicaid/iotagent-ul/blob/master/config.js#L119 default port for this agent is 4061. This PR fix it in Docker related stuff.

@jason-fox could you review? (Maybe I have missed some piece to update...) Thanks!

### CODE REVIEW

**Comment by jason-fox** [comment]
@fgalan, a quick grep reveals the following:

```


/iotagent-ul/bin/iotaULTester.js:
   45:         port: 4041,

/iotagent-ul/docker/README.md:
   46:         - "4041"
   49:         - "4041:4041"
   54:         - "IOTA_NORTH_PORT=4041"
   60:         - "IOTA_PROVIDER_URL=http://iot-agent:4041"

/iotagent-ul/docs/installationguide.md:
   66: docker run -d --link orion:orion --link mosquitto:mosquitto --link mongo:mongo -p 7896:7896 -p 4041:4041 telefonicaiot/iotagent-ul
   75: map the external IoT Agent North and South ports, for external calls: 4041 (NGSI Interactions

/iotagent-ul/test/config-test.js:
   51:         port: 4041
   59:     providerUrl: 'http://localhost:4041',

/iotagent-ul/test/subscriptionRequests/bidirectionalSubscriptionRequest.json:
    9:   "reference":"http://localhost:4041/notify",

/iotagent-ul/test/unit/amqpBinding-test.js:
  112:             url: 'http://localhost:4041/iot/services',

/iotagent-ul/test/unit/httpBinding-test.js:
  133:                 url: 'http://localhost:4041/iot/services',
  176:                 url: 'http://localhost:4041/iot/devices/MQTT_UNPROVISIONED',
  473:                 url: 'http://localhost:4041/iot/services' ,
  523:                 url: 'http://localhost:4041/iot/services',

/iotagent-ul/test/unit/mqttBinding-test.js:
  101:                 url: 'http://localhost:4041/iot/services',

/iotagent-ul/test/unit/ngsiv2/amqpBinding-test.js:
  119:             url: 'http://localhost:4041/iot/services',

/iotagent-ul/test/unit/ngsiv2/config-test.js:
   54:         port: 4041
   63:     providerUrl: 'http://localhost:4041',

/iotagent-ul/test/unit/ngsiv2/httpBindings-test.js:
  180:             url: 'http://localhost:4041/iot/services',
  229:                 url: 'http://localhost:4041/iot/devices/UL_UNPROVISIONED',
  521:             url: 'http://localhost:4041/iot/services',
  572:             url: 'http://localhost:4041/iot/services',

/iotagent-ul/test/unit/ngsiv2/mqttBinding-test.js:
  136:                 url: 'http://localhost:4041/iot/services',

/iotagent-ul/test/unit/ngsiv2/subscriptionRequests/bidirectionalSubscriptionRequest.json:
   17:       "url":"http://localhost:4041/notify"
```

**Comment by fgalan** [comment]
...so maybe the place to fix is actually config.js xD

Let me check internally which number is the right one. @AlvaroVega what do you think?

**Comment by AlvaroVega** [comment]
Yes, UL port should be 4061

**Comment by fgalan** [comment]
Ok. I'll extend the fix in the PR and change all them 4041 -> 4061

**Comment by fgalan** [comment]
FYI @dcalvoalonso 

Just to let you know that we have somehow "officialized" 4061 as the north port for UL agent.

**Comment by dcalvoalonso** [comment]
Ok, I take note! Thanks for the warning! :)

**Pull request merged**
