### PR TITLE
Fix #320 - Reverting to previous MQTT functionality from 1.7.0

### LINKED ISSUE #320: DEVICE_GROUP_NOT_FOUND when I provision service group
What can be the reason that I receive DEVICE_GROUP_NOT_FOUND  when I provision a service group?  

I am going through the tutorial and my setup is the same as in https://github.com/Fiware/tutorials.IoT-over-MQTT (I cloned repository and then `./services create` `./services start`).

When I look at IoT Agent logs (`docker logs <iot_agent> --follow`):

```
time=2019-01-04T10:59:41.633Z | lvl=DEBUG | corr=054a31d7-a532-442a-bb37-3ed3c739970d | trans=054a31d7-a532-442a-bb37-3ed3c739970d | op=IoTAgentNGSI.GenericMiddlewares | srv=openiot | subsrv=/ | msg=Request for path [/iot/services] from [localhost:4041] | comp=IoTAgent
time=2019-01-04T10:59:41.634Z | lvl=DEBUG | corr=054a31d7-a532-442a-bb37-3ed3c739970d | trans=054a31d7-a532-442a-bb37-3ed3c739970d | op=IoTAgentNGSI.GenericMiddlewares | srv=openiot | subsrv=/ | msg=Body:
{
    "services": [
        {
            "apikey": "4jggokgpepnvsb2uv4s40d59ov",
            "cbroker": "http://orion:1026",
            "entity_type": "Thing",
            "resource": ""
        }
    ]
}
 | comp=IoTAgent
time=2019-01-04T10:59:41.637Z | lvl=DEBUG | corr=054a31d7-a532-442a-bb37-3ed3c739970d | trans=054a31d7-a532-442a-bb37-3ed3c739970d | op=IoTAgentNGSI.DeviceGroupService | srv=openiot | subsrv=/ | msg=Creating new set of 1 services | comp=IoTAgent
time=2019-01-04T10:59:41.637Z | lvl=DEBUG | corr=054a31d7-a532-442a-bb37-3ed3c739970d | trans=054a31d7-a532-442a-bb37-3ed3c739970d | op=IoTAgentNGSI.DeviceGroupService | srv=openiot | subsrv=/ | msg=validateGroup {"apikey":"4jggokgpepnvsb2uv4s40d59ov","cbroker":"http://orion:1026","resource":"","type":"Thing","service":"openiot","subservice":"/"} | comp=IoTAgent
time=2019-01-04T10:59:41.637Z | lvl=DEBUG | corr=054a31d7-a532-442a-bb37-3ed3c739970d | trans=054a31d7-a532-442a-bb37-3ed3c739970d | op=IoTAgentNGSI.MongoDBGroupRegister | srv=openiot | subsrv=/ | msg=Looking for group params ["resource","apikey"] with queryObj {"apikey":"4jggokgpepnvsb2uv4s40d59ov"} | comp=IoTAgent
time=2019-01-04T10:59:41.647Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Device group for fields [["resource","apikey"]] not found: [{"apikey":"4jggokgpepnvsb2uv4s40d59ov"}] | comp=IoTAgent
time=2019-01-04T10:59:41.647Z | lvl=ERROR | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.Alarms | srv=n/a | subsrv=n/a | msg=Raising [MONGO-ALARM]: {"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group","code":404} | comp=IoTAgent
time=2019-01-04T10:59:41.647Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceGroupService | srv=n/a | subsrv=n/a | msg=generateDuplicateHander error [object Object] and foundGroup undefined | comp=IoTAgent
time=2019-01-04T10:59:41.655Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Storing device group with id [5c2f3c9d29eeb70011b40a74], type [Thing], apikey [4jggokgpepnvsb2uv4s40d59ov] and resource [] | comp=IoTAgent
time=2019-01-04T10:59:41.671Z | lvl=ERROR | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.Alarms | srv=n/a | subsrv=n/a | msg=Releasing [MONGO-ALARM] | comp=IoTAgent
time=2019-01-04T10:59:41.671Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.IOTAMService | srv=n/a | subsrv=n/a | msg=Looking for bindings for the function [configurationHandler] and protocol [null] | comp=IoTAgent
time=2019-01-04T10:59:41.673Z | lvl=DEBUG | corr=054a31d7-a532-442a-bb37-3ed3c739970d | trans=054a31d7-a532-442a-bb37-3ed3c739970d | op=IoTAgentNGSI.DomainControl | srv=openiot | subsrv=/ | msg=response-time: 69 | comp=IoTAgent
```

1) Is this a problem? (On the other hand I receive 201 created status) and also when I make get on `http://localhost:4041/iot/services` this service is found as below:

```
{
    "count": 1,
    "services": [
        {
            "commands": [],
            "lazy": [],
            "attributes": [],
            "_id": "5c2f3c9d29eeb70011b40a74",
            "resource": "",
            "apikey": "4jggokgpepnvsb2uv4s40d59ov",
            "service": "openiot",
            "subservice": "/",
            "__v": 0,
            "static_attributes": [],
            "internal_attributes": [],
            "entity_type": "Thing"
        }
    ]
}
```

2) Unfortunately, I get the same  DEVICE_GROUP_NOT_FOUND also when I provision my sensor (making curl from mentioned tutorial):

````
`curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Thing",
     "resource":    ""
   }
 ]
}'
````

Logs:

```
time=2019-01-04T11:43:12.915Z | lvl=DEBUG | corr=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | trans=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | op=IoTAgentNGSI.GenericMiddlewares | srv=openiot | subsrv=/ | msg=Request for path [/iot/devices] from [localhost:4041] | comp=IoTAgent
time=2019-01-04T11:43:12.915Z | lvl=DEBUG | corr=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | trans=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | op=IoTAgentNGSI.GenericMiddlewares | srv=openiot | subsrv=/ | msg=Body:
{
    "devices": [
        {
            "device_id": "motion001",
            "entity_name": "urn:ngsd-ld:Motion:001",
            "entity_type": "Motion",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "MQTT",
            "timezone": "Europe/Berlin",
            "attributes": [
                {
                    "object_id": "c",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refStore",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Store:001"
                }
            ]
        }
    ]
}
 | comp=IoTAgent
time=2019-01-04T11:43:12.916Z | lvl=DEBUG | corr=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | trans=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | op=IoTAgentNGSI.DeviceProvisioning | srv=openiot | subsrv=/ | msg=Handling device provisioning request. | comp=IoTAgent
time=2019-01-04T11:43:12.916Z | lvl=DEBUG | corr=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | trans=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=openiot | subsrv=/ | msg=Looking for group params ["service","subservice","type"] with queryObj {"service":"openiot","subservice":"/","type":"Motion"} | comp=IoTAgent
time=2019-01-04T11:43:12.920Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type"]] not found: [{"service":"openiot","subservice":"/","type":"Motion"}] | comp=IoTAgent
time=2019-01-04T11:43:12.920Z | lvl=ERROR | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.Alarms | srv=n/a | subsrv=n/a | msg=Raising [MONGO-ALARM]: {"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group","code":404} | comp=IoTAgent
time=2019-01-04T11:43:12.920Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.BidirectionalPlugin | srv=n/a | subsrv=n/a | msg=Extracting attribute list | comp=IoTAgent
time=2019-01-04T11:43:12.920Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.BidirectionalPlugin | srv=n/a | subsrv=n/a | msg=Sending bidirectionality subscriptions for device [motion001] | comp=IoTAgent
time=2019-01-04T11:43:12.921Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.IOTAMService | srv=n/a | subsrv=n/a | msg=Looking for bindings for the function [deviceProvisioningHandler] and protocol [null] | comp=IoTAgent
time=2019-01-04T11:43:12.921Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.IOTAMService | srv=n/a | subsrv=n/a | msg=Binding found for function [deviceProvisioningHandler] and protocol [null] | comp=IoTAgent
time=2019-01-04T11:43:12.921Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=n/a | subsrv=n/a | msg=Looking for device with id [motion001]. | comp=IoTAgent
time=2019-01-04T11:43:12.923Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=n/a | subsrv=n/a | msg=Device [motion001] not found. | comp=IoTAgent
time=2019-01-04T11:43:12.924Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Looking for group params ["service","subservice","type"] with queryObj {"service":"openiot","subservice":"/","type":"Motion"} | comp=IoTAgent
time=2019-01-04T11:43:12.925Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Device group for fields [["service","subservice","type"]] not found: [{"service":"openiot","subservice":"/","type":"Motion"}] | comp=IoTAgent
time=2019-01-04T11:43:12.926Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=deviceData: {"id":"motion001","type":"Motion","name":"urn:ngsd-ld:Motion:001","service":"openiot","subservice":"/","active":[{"object_id":"c","name":"count","type":"Integer"}],"staticAttributes":[{"name":"refStore","type":"Relationship","value":"urn:ngsi-ld:Store:001"}],"timezone":"Europe/Berlin","protocol":"PDI-IoTA-UltraLight","transport":"MQTT","internalId":null,"subscriptions":[]} | comp=IoTAgent
time=2019-01-04T11:43:12.927Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=deviceData2: {"id":"motion001","type":"Motion","name":"urn:ngsd-ld:Motion:001","service":"openiot","subservice":"/","active":[{"object_id":"c","name":"count","type":"Integer"}],"staticAttributes":[{"name":"refStore","type":"Relationship","value":"urn:ngsi-ld:Store:001"}],"lazy":null,"commands":[],"timezone":"Europe/Berlin","protocol":"PDI-IoTA-UltraLight","transport":"MQTT","internalId":null,"subscriptions":[]} | comp=IoTAgent
time=2019-01-04T11:43:12.928Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=Registering device into NGSI Service:
{
    "id": "motion001",
    "type": "Motion",
    "name": "urn:ngsd-ld:Motion:001",
    "service": "openiot",
    "subservice": "/",
    "active": [
        {
            "object_id": "c",
            "name": "count",
            "type": "Integer"
        }
    ],
    "staticAttributes": [
        {
            "name": "refStore",
            "type": "Relationship",
            "value": "urn:ngsi-ld:Store:001"
        }
    ],
    "lazy": null,
    "commands": [],
    "timezone": "Europe/Berlin",
    "protocol": "PDI-IoTA-UltraLight",
    "transport": "MQTT",
    "internalId": null,
    "subscriptions": []
} | comp=IoTAgent
time=2019-01-04T11:43:12.931Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=No Context Provider registrations found for unregister | comp=IoTAgent
time=2019-01-04T11:43:12.932Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=Creating initial entity in the Context Broker:
 {
    "url": "http://orion:1026/v1/updateContext",
    "method": "POST",
    "json": {
        "contextElements": [
            {
                "type": "Motion",
                "isPattern": "false",
                "id": "urn:ngsd-ld:Motion:001",
                "attributes": [
                    {
                        "name": "count",
                        "type": "Integer",
                        "value": " "
                    },
                    {
                        "name": "refStore",
                        "type": "Relationship",
                        "value": "urn:ngsi-ld:Store:001"
                    },
                    {
                        "name": "TimeInstant",
                        "type": "ISO8601",
                        "value": " "
                    }
                ]
            }
        ],
        "updateAction": "APPEND"
    },
    "headers": {
        "fiware-service": "openiot",
        "fiware-servicepath": "/",
        "fiware-correlator": "16a153ce-7f56-4716-b34b-0a80132b8d31"
    }
} | comp=IoTAgent
time=2019-01-04T11:43:12.935Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=executeWithSecurity | comp=IoTAgent
time=2019-01-04T11:43:12.936Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Looking for group params ["type"] with queryObj {"type":"Motion"} | comp=IoTAgent
time=2019-01-04T11:43:12.939Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Device group for fields [["type"]] not found: [{"type":"Motion"}] | comp=IoTAgent
time=2019-01-04T11:43:12.940Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=error {"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group","code":404} in get group device | comp=IoTAgent
time=2019-01-04T11:43:12.980Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=Initial entity created successfully. | comp=IoTAgent
time=2019-01-04T11:43:12.983Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=n/a | subsrv=n/a | msg=Storing device with id [motion001] and type [Motion] | comp=IoTAgent
time=2019-01-04T11:43:13.010Z | lvl=ERROR | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.Alarms | srv=n/a | subsrv=n/a | msg=Releasing [MONGO-ALARM] | comp=IoTAgent
time=2019-01-04T11:43:13.010Z | lvl=DEBUG | corr=16a153ce-7f56-4716-b34b-0a80132b8d31 | trans=16a153ce-7f56-4716-b34b-0a80132b8d31 | op=IoTAgentNGSI.DeviceProvisioning | srv=n/a | subsrv=n/a | msg=Device provisioning request succeeded | comp=IoTAgent
time=2019-01-04T11:43:13.013Z | lvl=DEBUG | corr=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | trans=5d95adfc-9e2d-4b6d-8616-67370c5248b4 | op=IoTAgentNGSI.DomainControl | srv=openiot | subsrv=/ | msg=response-time: 98 | comp=IoTAgent

```

### PR DESCRIPTION
**Pull request by jason-fox**
Only set default resource if using the HTTP Transport. Use blank otherwise.

### CODE REVIEW

**Comment by jason-fox** [comment]
Related - https://github.com/telefonicaid/iotagent-node-lib/pull/773

**Comment by mrutid** [comment]
I'm not 100% sure but I think that both transports MQTT/HTTP are always active simultaneously. You just need to specify a concrete transport for a given device if you want to send it commands, but for measures is not necessary. Have you take this into account?. Best.

**Comment by jason-fox** [comment]
When an MQTT measure is received it is processed by the[MQTTBinding.js](https://github.com/telefonicaid/iotagent-ul/blob/master/lib/bindings/MQTTBinding.js#L169)

The [receiving function](https://github.com/telefonicaid/iotagent-ul/blob/master/lib/commonBindings.js#L277) contains a hard coded `MQTT` transport:

```javascript
function mqttMessageHandler(topic, message) {
    messageHandler(topic, message, 'MQTT');
}
```

Similarly for [HTTP](https://github.com/telefonicaid/iotagent-ul/blob/master/lib/bindings/HTTPBindings.js#L260) the [transport](https://github.com/telefonicaid/iotagent-ul/blob/master/lib/bindings/HTTPBindings.js#L45) is defined in the call to retrieve the device.

Therefore if `retrieveDevice()` is called by a measure it will pass either `MQTT` or `HTTP`.  The logic for HTTP therefore remains as previously defined.

**Comment by jason-fox** [comment]
Withdrawing as the workaround in https://github.com/telefonicaid/iotagent-node-lib/pull/773 can be used instead.

**Pull request closed without merging**
