### PR TITLE
ADD Timeout for command calls

### PR DESCRIPTION
**Pull request by dmoranj**
Implements #97

### CODE REVIEW

**Comment by XavierVal** [comment]
LGTM

**Comment by Jagatjot** [comment]
@fgalan @XavierVal the commit was merged during release 1.1.0 and after that release why it was removed from the code? Do we need to show timeout parameter during the response command?

**Comment by fgalan** [comment]
Not sure what do you mean...

Maybe you mean that the code added in this PR

```
    if (config.getConfig().http.timeout) {
        options.timeout = config.getConfig().http.timeout;
    }
```

is no longer in the version of HTTPBindings.js in master branch?

**Comment by Jagatjot** [comment]
@fgalan Yes, I isn't there since 1.2.0 release. It was just added during 1.1.0 release

**Comment by fgalan** [comment]
So you mean that it has never been included in master branch? Only in release/1.1.0 branch?

**Comment by Jagatjot** [comment]
Yes u are right.

**Comment by Jagatjot** [comment]
@fgalan I investigated the files HTTPBinding.js and config.js. When I uncomment the timeout value in config.js as defined in this PR and try to fetch the value in HTTPBindings.js. The timeout value is undefined.

**Pull request merged**
