### PR TITLE
Feature/docker hardening

### PR DESCRIPTION
**Pull request by jason-fox**
This PR fixes several issues raised by [docker/docker-bench-security](https://github.com/docker/docker-bench-security)

- Add missing `HEALTHCHECK` - currently just a ping to `/iota/about`, but could be expanded
- Add standard metadata build `LABEL` (see [opencontainers.org](https://github.com/opencontainers/opencontainers.org))
- Remove **deprecated** `MAINTAINER` - replace with `LABEL` 
- Create two-stage build process  using a **Distroless** build:

     -    Remove [disto](https://medium.com/@dwdraju/distroless-is-for-security-if-not-for-size-6eac789f695f) 	
     -    Run as anonymous user 
     -    Set `NODE_ENV` to development/production

This reduces the image size from 194MB to 127MB

You can no longer run bash within the container

```console
docker exec -it iotagent-ul /bin/bash
```
```text
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
```

Ensure that Dockerfile continues to follow best practice by linting on CI. Using [Hadolint](https://github.com/hadolint/hadolint)

Remove Docker Secret support from `entrypoint.sh` since it should be processed by Node not Bash. (see https://github.com/telefonicaid/iotagent-node-lib/pull/885)

### CODE REVIEW

**Comment by jason-fox** [comment]
It remains to be decided what should be done with the existing `entrypoint.sh` which is merely instantiating [pm2](https://pm2.keymetrics.io/).  This violates the _one-concern-per-docker-container_ rule and pushes the process restart logic into the container itself (which doesn't lie nicely with Docker Swarm or Kubernetes or current practices)

Personally I'd like to get rid of it from the Docker container altogether.  It is still possible to invoke it if the appropriate `ENV` is set, and the **one-stage** build process has been used.

```console
docker build --target build-env  -t iotagent-ul .
```

**Comment by jason-fox** [comment]
We can remove the  `entrypoint.sh` for pm2 and create three separate build targets to cover all scenarios:

1) Distroless Build - lightweight, secure, no bash
```console
 docker build -t fiware/iotagent-ul  .  
```

2) Debian Build - just builds the resource files in a Node container.
```console
docker build -t fiware/iotagent-ul --target=build-env .  
```

3) PM2 Build - runs the process using PM2
```console
docker build -t fiware/iotagent-ul --target=pm2-install . 
```

**Comment by jason-fox** [comment]
The documentation test failure is fixed by PR https://github.com/telefonicaid/iotagent-ul/pull/434

**Comment by jason-fox** [comment]
To maintain docker secrets support, this PR should be processed after https://github.com/telefonicaid/iotagent-node-lib/pull/885

**Comment by fgalan** [comment]
We are having a look at the modifications in the docker stuff involved in this PR (which I understand are of the same style than the ones proposed in other repos), especially from the point of view of potential problems/incompatibilities with our deployments. We hope to be able to provide some feedback soon.

Stay tuned...

CC: @AlvaroVega @IvanHdzC

**Comment by jason-fox** [comment]
@fgalan @AlvaroVega - This PR is ready for review

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Review by fgalan — APPROVED** [review]
LGTM

We are conducting right now some test with final result of this approach in IOTA-JSON. Once we confirm it's ok, we will merge this PR.

**Comment by fgalan** [comment]
After some final fixes (PR https://github.com/telefonicaid/iotagent-node-lib/pull/915) CI for IOTA-JSON worked, so we are merging now the rest of pending PRs related this.

**Pull request merged**
